### ISSUE TITLE
build not working

### ISSUE THREAD

**Issue by emma-eva** [JustSlavic/pinapl#2]
Plz add build info, thanks

**Comment by JustSlavic** [comment]
Hi! First, thank you for trying to build my project. I would not anticipated that anyone would use it, but since you tried, I added the small doc for build script in README.md.

The build script did not work because I made it to build without CRT from assembly language, that would only work on only one architecture, where I develop it (on a Raspberry pi).

I made that so build script would build with CRT by default, so probably it should work now, but I am not sure. If it can't, please send the error messages you get.

Thank you!
